# Generated by Django 5.0 on 2023-12-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField()),
                ('question_description', models.TextField(blank=True, null=True)),
                ('question_constrants', models.CharField(blank=True, max_length=50, null=True)),
                ('question_testcases_input', models.TextField(blank=True, null=True)),
                ('question_testcases_output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
